version: '1'

services:
  frontend:
    container_name: service_front_end
    bulid:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  hotdeal_crawl:
    container_name: service_hotdeal_crawl
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    networks:
      -app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

network:
  app-network:
    driver: bridge
